import React from 'react';

const TermsAndConditions = () => {
    return (
        <div className="container mx-auto py-10 px-4">
            <h2 className="text-center text-3xl font-bold mb-8">Terms and Conditions</h2>
            <div className="bg-white shadow-md rounded-lg p-6">
                <div className="prose max-w-none">
                    <p><strong>Terms of Use:</strong></p>
                    <p>SET OUT BELOW ARE THE TERMS OF USE WHICH GOVERN THE USAGE OF E-COMMERCE PLATFORM. YOU ARE REQUESTED TO CAREFULLY READ AND UNDERSTAND THESE TERMS OF USAGE THEY AFFECT YOUR RIGHTS AND IMPOSE CERTAIN PRE-CONDITIONS AND RESPONSIBILITIES TO BE FULFILLED BEFORE MAKING USE OF THIS E-COMMERCE PLATFORM.</p>
                    <br></br>
                    <p><strong>1. GENERAL</strong></p>
                    <br></br>
                    <ul>
                        <li>1.1 Welcome to our E-COMMERCE PLATFORM, www.mahaagromart.com (“<strong>E-COMMERCE PLATFORM</strong>”). The E-COMMERCE PLATFORM is owned by The Maharashtra Agro-Industries Development Corporation Limited, (“<strong>THE M.A.I.D.C.</strong>” or “<strong>We</strong>”), a company duly existing under the Companies Act, 2013 bearing CIN U05000MH1965SGC013380 and having its registered office at Krushi Udyog Bhavan, Aarey Milk Colony, Dinkarrao Desai Marg, Goregaon (East), Mumbai - 400 065, Maharashtra, India.</li>
                        <li>1.2 This document is an electronic record in terms of Information Technology Act, 2000, and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act 2000. This electronic record is generated by a computer system and does not require any physical or digital signature.</li>
                        <li>1.3 This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for accessory usage of the E-COMMERCE PLATFORM with domain name www.mahaagromart.com, including the related mobile application (MAHAAGRO MART).</li>
                        <li>1.4 If you are a visitor to the E-COMMERCE PLATFORM, then by merely accessing, browsing, logging into, or using the E-COMMERCE PLATFORM, you shall be deemed to have read, understood, and accepted the Terms of Use, and the Terms of Use shall therefore constitute a binding contractual arrangement between you and THE M.A.I.D.C.</li>
                        <li>1.5 A User’s or visitors use this E-COMMERCE PLATFORM are governed (“<strong>Terms of Use</strong>”), including any policies, directions, circular/s and guidelines as amended from time to time, which are incorporated by way of reference.</li>
                        <li>1.6 We assume, that in case you are:
                            <ul>
                                <li>I. helping another User who may be illiterate or who is not technologically savvy to use this E-COMMERCE PLATFORM;</li>
                                <li>II. are jointly using for yourself and other Users; or</li>
                                <li>III. Using the E-COMMERCE PLATFORM as a representative of a User who is an incorporated/juristic entity, then it shall be deemed that such User and/or co-User has also read, understood, and accepted these Terms of Use.</li>
                            </ul>
                        </li>
                        <li>1.7 By impliedly or expressly accepting these Terms of Use, the User also accepts and agrees to be bound by the policies of THE M.A.I.D.C. including but not limited to the privacy policy, as amended from time to time which can be accessed from this E-COMMERCE PLATFORM.</li>
                        <li>1.8 THE M.A.I.D.C. reserves the right, at its sole discretion, to change and modify, add or remove any portion of the Terms of Use or replace the entire Terms of Use at any time without any prior notice to any visitor or User.</li>
                        <li>1.9 The User or visitor shall periodically review the Terms of Use available on the E-COMMERCE PLATFORM. User’s continued use of the E-COMMERCE PLATFORM, after posting any changes, replacement, revisions, or modifications shall mean that the User has read, understood and accepted the changes, replacements, revisions, or modifications to the Terms of Use.</li>
                        <li>1.10 As long as you comply with the Terms of Use, policies, directions, circular/s and guidelines THE M.A.I.D.C. grants a User a personal, non-exclusive, non-transferrable, limited privilege to enter and use the E-COMMERCE PLATFORM.</li>
                        <li>1.11 The E-COMMERCE PLATFORM and the services of THE M.A.I.D.C. are offered only to residents of the Republic of India.</li>
                        <li>1.12 Whenever a Buyer or Seller, uses any service of THE M.A.I.D.C. either through the E-COMMERCE PLATFORM or otherwise, it will be subject to the Terms of Use, including any policies, directions, circular/s and guidelines as amended from time to time, which are incorporated by way of reference.</li>
                        <li>1.13 The sale/purchase or listing, provisioning of products and any other transaction on the E-COMMERCE PLATFORM shall be subject to prevailing laws and rules, regulation, policies, notifications, circular/s, directions, orders, judgments, rulings, which have the force of law and are in force (“<strong>Applicable Laws</strong>”). Wherever, there is an inconsistency between the Terms of Use and Applicable Laws, the Applicable Laws will always prevail.</li>
                        <li>1.14 For the purpose of these Terms of Use, wherever the context so requires:
                            <ul>
                                <li>I. “Seller” shall mean THE M.A.I.D.C., where it sells its own products and goods, or any natural or legal person who uses or intends to use the E-COMMERCE PLATFORM to sell their products;</li>
                                <li>II. “Buyer” shall mean natural or legal person who uses or intends to use the E-COMMERCE PLATFORM to buy products listed on the E-COMMERCE PLATFORM;</li>
                                <li>III. "You" or “User" shall include, without limitation, sellers who list their products and services on the E-COMMERCE PLATFORM (seller-user), buyers including the retailers, who buy products listed in the E-COMMERCE PLATFORM (buyer-user), etc. User is not confined to the final user of products and services and it may include a retailer covered under Fertilizer Control Order 1985, the Insecticides Act 1968, Seed Act 1966, and any rules, amendments guidelines revised from time to time shall be observed by the seller and buyer as per provisions.</li>
                                <li>IV. “Seller User Agreement” shall mean the individual agreement in format provided as Annexure-A that the User, who is a Seller, shall enter with THE M.A.I.D.C., if such User’s cumulative turnover over the E-COMMERCE PLATFORM (inclusive of all taxes) is at least Rs. 1,00,000/- as part of the registration process; and</li>
                                <li>V. “Promotional Services” shall mean services provided by THE M.A.I.D.C. to the Seller where THE M.A.I.D.C. promotes the products of such Seller on the E-COMMERCE PLATFORM, for a fee and on terms mutually agreed basis; and </li>
                                <li>VII.  “E-COMMERCE PLATFORM Usage Fees” shall mean the fees payable by the Seller, as per the Seller User Agreement or communicated to the Seller by email.</li>
                                <li>VIII.  The User hereby acknowledges and agrees that the User shall not, without THE M.A.I.D.C.’s prior written approval, in any manner, by any media or at any time issue or authorize the issuance of any news stories or publicity relating to the Platform which is: (i) Confidential Information; (ii) information about any disputes persisting between the User and THE M.A.I.D.C.; and (iii) derogatory, scandalous, or controversial remarks on the Platform or THE M.A.I.D.C. as used herein, “Confidential Information” includes, but is not limited to any information, data, documents, creative elements, technological processes or other materials of any kind or nature in any way related to the Project from any source or for any reasons, including without limitation, as acquired by User.</li>
                                <li>IX.  THE M.A.I.D.C. shall not be responsible or liable for any kind of misuse or indiscriminate use of good and services available on the e-commerce platform and the user shall carry entire liabilities out such mishaps, loss of life, miscarriages, poisoning, accidents or any other consequences arising from above nature of events.</li>
                                <li>X. The Seller User and Buyer User shall indemnify the MAIDC from all sort of losses, legal implications and consequences and events.</li>
                                <li>XI.  In case if Sellers opt to have to limit its sales to particular dealers, state, region, revenue Division of the state or product wise limitations through the platform, they may do so by mutual consent of THE M.A.I.D.C.</li>
                                <li>XII.  In the event that user chooses to cancel an order midway through the delivery process, a cancellation penalty equivalent to 5% of the total order value shall be applied.</li>
                                <li>XIII.  The logistic partner shall make a minimum of three delivery attempts to the designated delivery address if the user is unavailable to receive the order.</li>
                                <li>XIV.  The vendor shall be responsible for maintaining accurate stock levels of all products for sale. In the event that a buyer places an order for a product that is shown as a stock, but the vendor does not have the stock available, the vendor shall be held accountable. A penalty equivalent to 30% of the total order value shall be imposed on the vendor for failure to maintain stock levels.</li>
                                <li>XV.  For food products, it is responsibility of the vendor to ensure that all necessary documents, including but not limited to health and safety certificates, ingredient lists and expiration dates are readily available. Failure to provide the required documentation upon request by the regulator authorities or the buyer shall be considered a breach of responsibility on the part of the vendor. Any resulting penalties, fines or legal consequences arising out from the absence of such documentation shall be borne solely by the vendor. It is incumbent upon the vendor to maintain accurate and up-to-date documentation for all good products offered for sale.</li>
                                <li>XVI.  In case of Pesticide and Fertilizers, the vendor is obligated to possess and provide all requisite selling documents.</li>
                                <li>XVII. In instances where the weight of the product upon delivery is found to be less that the specified or advertised weight the responsibility for the discrepancy shall lie solely with the vendor.</li>
                                <li>XVIII. In the event that the vendor pays less Goods and Services Tax (GST) than required by law for any transaction, the responsibility for rectifying the shortfall and bearing any associated penalties shall rest solely with the vendor. The vendor is obligated to ensure full compliance with GST regulations and to accurately calculate and remit the appropriate GST amount for all transactions. Any penalties imposed by tax authorities due to underpayment of GST shall be the sole responsibility of the vendor and the vendor shall promptly rectify the discrepancy by paying the outstanding GST amount</li>
                                <li>XIX.  If the vendors gives free delivery, the vendor will be responsible and the delivery charges will be deducted accordingly.</li>

                            </ul>
                        </li>
                    </ul>
                    <br></br>
                    <p><strong>2. USER’S REPRESENTATIONS & WARRANTIES</strong></p>
                    <br></br>
                    <ul>
                        <li>2.1 You represent to THE M.A.I.D.C.  that:</li>
                        <li>I. You are 18 years of age and that you are competent to contract under the law;</li>
                        <li>II. The information and documents provided by you to THE M.A.I.D.C.  is true and correct and you undertake to keep such information and documents updated at all times you intend to use the E-COMMERCE PLATFORM or services by THE M.A.I.D.C.</li>
                        <li>III. in case you are using the E-COMMERCE PLATFORM as a representative of either an User who is an incorporated/juristic entity, or individual User who is illiterate or not technologically savvy, or you are one of the joint-Users, then you are duly authorized to make transactions and accept obligations on behalf of such User or any other Co-Users who may be a part of your transaction.</li>
                        <li>IV. No application for insolvency resolution against you has been admitted under the Insolvency and Bankruptcy Code 2016.</li>
                        <li>V. You are authorized to list the products; you intend to sell on the E-COMMERCE PLATFORM.
                            <ul>
                                <li>VI. You represent that you have adequate rights in respect of the content including trademarks, logos, photographs, videos, and other works you upload on the E-COMMERCE PLATFORM.</li>
                                <li>VII. You are not prohibited under any law, policy, judgment or order applicable to you or otherwise to undertake the transaction on this E-COMMERCE PLATFORM or utilize the services of THE M.A.I.D.C. Or make payments to any person in respect to services related to the E-COMMERCE PLATFORM.</li>
                                <li>2.2 If User uses the E-COMMERCE PLATFORM, User shall be responsible for maintaining the confidentiality of its account and password and for restricting access to its computer or other devices to prevent unauthorized access to its account.</li>
                            </ul>
                        </li>
                        <li>2.3 User agrees to accept responsibility for all activities that occur under User’s account or password, and User agrees, inter alia, to:</li>
                        <li>I.&nbsp; Provide true, accurate, current and complete information about User as prompted by THE M.A.I.D.C. ’s registration form (such information being the "<strong>Registration Data</strong>");</li>
                        <li>II.  Include any of User’s contact details such as mobile number, geographical address, email address, User ID while registering as a User.</li>
                        <li>III. Maintain and promptly update the Registration Data to keep it true, accurate, current and complete at all times;</li>
                        <li>iV. Immediately notify THE M.A.I.D.C.  of any unauthorized use of User’s password or account or any other breach of security;</li>
                        <li>V.  Ensure that User exits or logs out from its account at the end of each session; and</li>
                        <li>VI  All communications received from THE M.A.I.D.C. for contractual purposes in an electronic form via any email address that the User may have indicated to THE M.A.I.D.C.</li>
                        <li>VII  All modifications, agreements, notices, disclosures, and other communications that THE M.A.I.D.C. provides electronically, shall satisfy any legal requirement that such communications should be in writing.
                            <ul>
                                <li>2.4 The User’s mobile phone number and/or e-mail address is treated as your primary identifier on the E-COMMERCE PLATFORM. It is the User’s responsibility to ensure that your mobile phone number and your email address is up to date on the E-COMMERCE PLATFORM at all times. The User agrees to notify us promptly if your mobile phone number or e-mail addresses changes by updating the same on the E-COMMERCE PLATFORM through one time password verification.</li>


                            </ul>
                        </li>
                    </ul>

                    <br></br>
                    <p><strong>3. SELLER’S AGREEMENT & COVENANTS</strong></p>
                    <br></br>
                    <p>
                        Where the Seller’s cumulative turnover over the E-COMMERCE PLATFORM (inclusive of all taxes) is at least Rs. 1,00,000/-, then such Seller shall upon receiving instructions from THE M.A.I.D.C., after payment of stamp duty of requisite value, execute the Seller User Agreement before Notary and send the original Seller User Agreement to THE M.A.I.D.C.
                    </p>
                    <h2>3.2 Terms of Use for Turnover Less Than Rs. 1,00,000/-</h2>
                    <p>
                        Where the Seller’s cumulative turnover over the E-COMMERCE PLATFORM (inclusive of all taxes) is less than Rs. 1,00,000/-, then such Seller shall be bound by these Terms of Use by merely creating a User account, logging in, or using the E-COMMERCE PLATFORM.
                    </p>
                    <h2>3.3 Seller’s Responsibilities</h2>
                    <ul>
                        <li>
                            Ensure that descriptions, images, and other content pertaining to products, goods, or services on the E-COMMERCE PLATFORM are accurate and correspond directly with the appearance, nature, quality, purpose, and other general features of such goods or services including proper measurement descriptions as required under law;
                        </li>
                        <li>
                            Be responsible to raise a proper G.S.T. invoice upon the Buyer and provide such other documents or certificates which the Buyer may require to produce for the purpose of further sale or export.
                        </li>
                        <li>
                            Be responsible to collect any taxes, G.S.T. or other levies from the Buyer and deposit the same to the relevant authorities.
                        </li>
                        <li>
                            Be responsible to resolve the grievance of the Buyer as per prevailing law.
                        </li>
                        <li>
                            Participate in the grievance redressal mechanism of THE M.A.I.D.C. and extend full cooperation to resolve any outstanding disputes with the Buyer.
                        </li>
                        <li>
                            Duly comply with all Applicable Laws including but not limited to:
                            <ul>
                                <li>The Consumer Protection Act, 2019 and all applicable rules thereunder including the Consumer Protection (E-Commerce) Rules, 2020.</li>
                                <li>Legal Metrology Act, 2009 and all applicable rules thereunder including the Legal Metrology (Packaged Commodities) Rules, 2011.</li>
                                <li>The Sale of Goods Act, 1930;</li>
                                <li>Prevention of Food Adulteration Act, 1954;</li>
                                <li>Drugs and Cosmetics Rules, 1945;</li>
                                <li>Seeds Act, 1966,</li>
                                <li>Essential Commodities Act, 1955;</li>
                                <li>Fertilizer Control, Order 1985;</li>
                                <li>The Insecticides Act 1968;</li>
                                <li>The Food Safety and Standards Act, 2006; and</li>
                                <li>Information Technology Act, 2000,</li>
                            </ul>
                            As amended from time to time, and follow the Terms of Use, policies, directions, circulars, or guidelines issued by THE M.A.I.D.C. from time to time.
                        </li>
                    </ul>
                    <h2>3.4 Product Listing Information</h2>
                    <p>The Seller shall be responsible to see that the product listing page shall display the following information:</p>
                    <ul>
                        <li>All contractual information required to be disclosed by law;</li>
                        <li>Total price in single figure of any goods or services, along with the breakup price for the goods or services, showing all the mandatory and voluntary charges such as delivery charges, postage and handling charges, conveyance charges and the applicable tax, as applicable.</li>
                        <li>All mandatory notices and information provided by applicable laws, and the expiry date of the good being offered for sale, wherever applicable.</li>
                        <li>All relevant details about the products, goods, and services offered for sale by the Seller including country of origin which are necessary for enabling the consumer to make an informed decision at the prepurchase stage;</li>
                        <li>The name and contact numbers, and designation of the grievance officer for consumer grievance redressal or for reporting any other matter, and the P.A.N. and G.S.T.I.N.(if applicable) should be displayed.</li>
                        <li>Name and details of importer, and guarantees related to the authenticity or genuineness of the imported products.</li>
                        <li>Accurate information related to terms of exchange, returns, and refund including information related to costs of return, refund and shipping in a clear and accessible manner.</li>
                        <li>Relevant details related to delivery and shipment of such products, goods, or services.</li>
                        <li>Any relevant guarantees or warranties applicable to such products, goods, or services.</li>
                        <li>The name of your business, whether registered or not, your geographic address, and any customer care number;</li>
                        <li>Concerning the declarations required of sub-rule (1) of Rule 6 of the Legal Metrology (Packaged Commodities) Rules, 2011.</li>
                        <li>The terms governing return, refund, exchange, warranty and guarantee, delivery and shipment, modes of payment, taxes chargeable so that the Buyer shall be able to make informed decision.</li>
                    </ul>
                    <h2>3.5 Storage of Goods in warehouse, assurance of increase in sale, fees for advertising on the E-COMMERCE PLATFORM</h2>
                    <ul>
                        <li>The Seller’s goods for sale may be stored in the warehouse of THE M.A.I.D.C. at convenience for speedy deliveries at PIN code decided by THE M.A.I.D.C.;</li>
                        <li>Also, THE M.A.I.D.C. shall not assure or warrants increase in sale on the E-COMMERCE PLATFORM. The Seller shall put its efforts for promotional schemes, offers and discounts from time to time to ensure effective sales; and</li>
                        <li>THE M.A.I.D.C. may charge appropriate fees for advertising Seller’s products and services on the E-COMMERCE PLATFORM.</li>
                    </ul>
                    <br></br>
                    <p><strong>4. BUYER’S AGREEMENT & COVENANTS</strong></p>
                    <br></br>
                    <p>
                        The Buyer who intends to purchase products on E-COMMERCE PLATFORM shall be bound by these Terms of Use by a mere creation of a User account, logging in, or placing an order using the E-COMMERCE PLATFORM without any further action.
                    </p>
                    <h2>4.2 Buyer’s Responsibilities</h2>
                    <ul>
                        <li>Duly comply with all applicable laws, rules, regulations, and follow the Terms of Use, policies, directions, circulars, or guidelines issued by THE M.A.I.D.C. from time to time;</li>
                        <li>Proactively check all the terms and information, and seek clarifications from the Seller before entering into a transaction or placing an order with the Seller;</li>
                        <li>Be responsible to resolve the grievance of the Seller as per prevailing law; and</li>
                        <li>Participate in the grievance redressal mechanism of THE M.A.I.D.C. and extend full cooperation to resolve any outstanding disputes with the Seller.</li>
                    </ul>
                    <h2>4.3 KYC Requirement for Purchases Over Rs. 2,00,000/-</h2>
                    <p>
                        The Buyer whose cumulative purchase over the E-COMMERCE PLATFORM (inclusive of all taxes) is more than Rs. 2,00,000/- then such Buyer shall be obligated to provide your K.Y.C. documents to THE M.A.I.D.C. including but not limited to copies of P.A.N. card.
                    </p>
                    <br></br>
                    <p><strong>5. PAYMENT TERMS FOR BUYERS</strong></p>
                    <br></br>

                    <ul>
                        <li>
                            The Buyer may utilize the services of the payment gateway available on the E-COMMERCE PLATFORM to make payments for the order/transactions and shall be liable to pay a service fee to the payment gateway provider depending on the mode of payment selected.
                        </li>
                        <li>
                            The Buyer agrees and understands that the charges on a credit cards/debit cards/e-wallet/UPI or bank account or any other payment or settlement method made for any products purchased through E-COMMERCE PLATFORM are irrevocable, undisputable and may not be charged back, contested or challenged now or in the future, doing so is a material breach of this Terms of Use, for which THE M.A.I.D.C. would be entitled to attorney fees, costs, and fees associated with addressing a chargeback in addition to the amount challenged. The Buyer further agrees that the proof of purchase provided by THE M.A.I.D.C.is all that is necessary to establish to the credit card agency or banking institution to deny a chargeback to such Buyer.
                        </li>
                    </ul>
                    <br></br>
                    <p><strong>6. PAYMENT TERMS FOR SELLERS</strong></p>
                    <br></br>

                    <ul>
                        <li>All payments to Sellers Users for orders/transactions that take place between the 1st to 15th of every month should be settled by the 30th day of the same month.</li>
                        <li>All payments to Sellers for orders/transactions that take place between the 15th to the 30thof the month should be settled by the 15th day of the subsequent month.</li>
                        <li>
                            The Seller agrees and understands that the charges on a credit cards/debit cards/e-wallet/UPI or bank account or any other payment or settlement method made through E-COMMERCE PLATFORM are irrevocable, undisputable and may not be charged back, contested or challenged now or in the future, and doing so is a material breach of this Terms of Use, for which THE M.A.I.D.C. would be entitled to attorney fees, costs, and fees associated with addressing a chargeback in addition to the amount challenged.
                        </li>
                        <li>
                            The Seller further agrees that proof of service provided by THE M.A.I.D.C. is all that is necessary to establish to the credit card agency or banking institution to deny a chargeback to such Seller.
                        </li>
                        <li>
                            In respect of any payments being made by the Seller to THE M.A.I.D.C., the Seller shall always be responsible for bearing any costs, charges, or damages payable by THE M.A.I.D.C. to the Payment Gateway Service Provider or the Bank or credit card agency due to such Seller’s fraud, dishonour by the Seller of any cheque issued in favour of THE M.A.I.D.C., or electronic payment method such E.C.S., e-mandate charges, NACH, etc. issued in favour M.A.I.D.C., in addition to other legal compensation payable under these terms and available to THE M.A.I.D.C. under law.
                        </li>
                        <li>The Seller shall be liable to pay towards simple interest of 10% per annum on any delayed payments to THE M.A.I.D.C. towards any liquidated damages.</li>
                        <li>The Seller shall be liable to pay E-COMMERCE PLATFORM Usage Fees, and fees for Promotional Services, and Warehousing Services, to THE M.A.I.D.C. on the terms that are mutually agreed separately.</li>
                    </ul>

                    <br></br>
                    <p><strong>7. PAYMENT GATEWAY SERVICES</strong></p>
                    <br></br>

                    <ul>
                        <li>
                            You have acquainted yourself with the terms and conditions and privacy policy of such payment gateway provider, before using the payment gateway which can be seen here: [please insert link to payment gateway terms & conditions]
                        </li>
                        <li>
                            THE M.A.I.D.C. does not make any representation, warranties, or guarantees in respect to the service provided by it or the E-COMMERCE PLATFORM or the services/products of the third-party service provider listed on the E-COMMERCE PLATFORM. The information in relation to third party service provider such as payment gateway charges are provided are on an “as is” basis and you agree to use these third-party services at your own risk.
                        </li>
                        <li>
                            You agree that where you use a payment gateway to make payments, shall be liable to process the registration only after receiving a confirmation of your payment, from the payment gateway. If for any reason, the payment gateway fails to provide a confirmation of your payment, your order / transaction may not be processed.
                        </li>
                        <li>
                            You agree that you won’t hold THE M.A.I.D.C. liable for any loss or damage caused due to the payment gateway’s failure, or failed transaction, any fraud transaction, or any destruction, theft, or leak of any data including personal data from the payment gateway’s application on the E-COMMERCE PLATFORM or the payment gateway’s database.
                        </li>
                    </ul>
                    <br></br>
                    <p><strong>8. INTELLECTUAL PROPERTY RIGHTS, PHOTOGRAPHS, & VIDEOS</strong></p>
                    <br></br>

                    <ul>
                        <li>
                            You grant a non-exclusive royalty-free license to THE M.A.I.D.C. to utilize your trademark, brand name, logo of any product, goods, or services that you intend to sell on the E-COMMERCE PLATFORM and any written or artistic works, photographs, music, songs, or videos that you upload on the E-COMMERCE PLATFORM (all collectively referred to as “User Content”) for publication and marketing within the territory of the Republic of India for the term of your User Agreement or termination of your User account.
                        </li>
                        <li>
                            You expressly consent to the usage or publication of your User Content on THE M.A.I.D.C.’s website, any social networking websites, blogs, video hosting websites, or in any electronic or print media including but not limited to brochures, pamphlets, advertising material, promotional videos, etc. You expressly waive the condition of obtaining your prior consent to such usage or publication and / or asking for payment/ remuneration in respect of such User Content.
                        </li>
                    </ul>
                    <h2>8.3 THE M.A.I.D.C. does not, and shall never be under any obligation:</h2>
                    <ul>
                        <li>To maintain or store any User Content in any specific manner;</li>
                        <li>To pay compensation for any User Content; or</li>
                        <li>To publish or utilize any User Content in any specific manner.</li>
                    </ul>
                    <br></br>
                    <p><strong>9. MODIFICATION, REPLACEMENT, AND SUBSTITUTION OF THE TERMS OF USE</strong></p>
                    <br></br>

                    <ul>
                        <li>
                            THE M.A.I.D.C. may publish certain policies, direction, circular, guidelines or additional terms and conditions for a class of transactions which would be in addition or supplemental to the Terms of Use and will be deemed to be a part of your contractual arrangement with THE M.A.I.D.C.
                        </li>
                        <li>
                            THE M.A.I.D.C. also reserves the right to unconditionally amend, modify, or replace the Terms of Use or any guidelines or additional terms and conditions without any personal prior notice to you. You are therefore requested to keep yourself updated with the same. You can review the most current version of the Terms of Use at any time on this page.
                        </li>
                    </ul>
                    <br></br>
                    <p><strong>10. USAGE AND POSTING CONTENTS ON THE E-COMMERCE PLATFORM</strong></p>
                    <br></br>

                    <ul>
                        <li>Belongs to another person and to which User does not have any right to -</li>
                        <li>
                            Is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, pedophilic, libelous, invasive of another's privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever.
                        </li>
                        <li>Involves the transmission of "junk mail", "chain letters", or unsolicited mass mailing or "spamming".</li>
                        <li>Promotes illegal activities or conduct that is abusive, threatening, obscene, defamatory or libelous.</li>
                        <li>
                            Infringes upon or violates any third party's rights including, but not limited to, intellectual property rights, rights of privacy (including without limitation unauthorized disclosure of a person's name, email address, physical address or phone number) or rights of publicity.
                        </li>
                        <li>Contains restricted or password-only access pages, or hidden pages or images (those not linked to or from another accessible page).</li>
                        <li>Provides instructional information about illegal activities such as making or buying illegal weapons, violating someone's privacy, or providing or creating computer viruses.</li>
                        <li>Contains video, photographs, or images of another person (with a minor or an adult).</li>
                        <li>
                            Tries to gain unauthorized access or exceeds the scope of authorized access to the E-COMMERCE PLATFORM or to profiles, blogs, communities, account information, bulletins, friend request, or other areas of the E-COMMERCE PLATFORM or solicits passwords or personal identifying information for commercial or unlawful purposes from other Users.
                        </li>
                        <li>Interferes with another User's use and enjoyment of the E-COMMERCE PLATFORM.</li>
                        <li>
                            Infringes any patent, trademark, copyright or other proprietary rights or third party's trade secrets or rights of publicity or privacy or shall not be fraudulent or involve the sale of counterfeit or stolen products.
                        </li>
                        <li>Violates any Applicable law for the time being in force.</li>
                        <li>
                            Threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognizable offence or prevents investigation of any offence or is insulting any other nation.
                        </li>
                        <li>Is false, inaccurate or misleading.</li>
                        <li>
                            Creates liability for THE M.A.I.D.C. or cause THE M.A.I.D.C. to lose (in whole or in part) the services of internet service provider of THE M.A.I.D.C. ("ISPs") or other suppliers.
                        </li>
                        <li>Contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer resource.</li>
                    </ul>

                    <li>10.2 THE M.A.I.D.C. functions as an intermediary which is limited to providing access to a E-COMMERCE PLATFORM for the Buyers and Seller to operate independently, and as such THE M.A.I.D.C. takes no responsibility and assume no liability for any comments posted by you or any third-party. It is not possible for THE M.A.I.D.C. to be aware of the contents of each product listed on the E-COMMERCE PLATFORM, or each comment or review that is displayed. Accordingly, THE M.A.I.D.C. operates on a "notice and takedown" basis.</li>
                    <li>10.3 If a User believes that the content on the E-COMMERCE PLATFORM is objectionable in nature then such User is requested to notify THE M.A.I.D.C. immediately by contacting THE M.A.I.D.C. through the modes available on the E-COMMERCE PLATFORM and THE M.A.I.D.C. will make all reasonable endeavors to remove such objectionable content complained about within a reasonable time.</li>
                    <li>10.4 If, at THE M.A.I.D.C. request, you send certain specific submissions (for example contest entries) or without a request from us you send creative ideas, suggestions, proposals, plans, or other materials, whether online, by email, by postal mail, or otherwise (collectively, 'comments'), you agree that we may, at any time, without restriction, edit, copy, publish, distribute, translate and otherwise use in any medium any comments that you forward to us.</li>
                    <li>10.5 THE M.A.I.D.C. does not, and shall never be under any obligation:
                        <ol>
                            <li>To maintain any comments in confidence.</li>
                            <li>To pay compensation for any comments.</li>
                            <li>To respond to any comments.</li>
                        </ol>
                    </li>
                    <li>10.6 THE M.A.I.D.C. shall in its sole discretion, at any time, remove, modify, or delete any portion or the entire Seller’s product listing from the E-COMMERCE PLATFORM without any prior reference or notice to the concerned Seller or any other User.</li>
                    <li>10.7 No User or visitor of this E-COMMERCE PLATFORM is permitted to do the following:
                        <ol>
                            <li>Systematic retrieval of data or other content from the E-COMMERCE PLATFORM to create or compile, directly or indirectly, a collection, compilation, database or directory without written permission from THE M.A.I.D.C.</li>
                            <li>Deciphering, decompiling, disassembling or reverse engineering any of the software comprising or in any way making up a part of the E-COMMERCE PLATFORM.</li>
                            <li>Attempting to bypass any measures of the E-COMMERCE PLATFORM designed to prevent or restrict access to the E-COMMERCE PLATFORM, or any portion of the E-COMMERCE PLATFORM.</li>
                            <li>Except as may be the result of standard search engine or internet browser usage, using or launching, developing or distributing any automated utility, including, without limitation, any spider, robot or bot, cheat mechanism, scraper or offline reader that accesses the E-COMMERCE PLATFORM, or using or launching any unauthorized script or other software.</li>
                            <li>Engaging in any automated use of the system, such as using any data mining, robots, scrapping or similar data gathering and extraction tools;</li>
                            <li>Using the E-COMMERCE PLATFORM’s service to build a competing service.</li>
                        </ol>
                    </li>
                    <br></br>
                    <p><strong>11. RETURN & REPLACEMENT :</strong></p>
                    <br></br>

                    <ol>
                        Replacement is the action or process of replacing something in place of another. A Buyer can request for replacement whenever he is not satisfied with the item, for reason being:
                        <ul>
                            <li>Damaged in shipping.</li>
                            <li>Defective item.</li>
                            <li>Item(s) missing; and</li>
                            <li>Wrong item shipped.</li>
                        </ul>

                        <li>The Seller can always accept the return irrespective of the policy.</li>
                        <li>Buyer needs to raise the replacement request within the return period applicable to the respective product.</li>
                        <li>The Buyer has to raise a replacement request by contacting THE M.A.I.D.C. and give the “reason for rejection” and order details.</li>
                        <li>An intimation shall be provided to Seller seeking either "approval" or "rejection" of the replacement request.</li>
                        <li>In case the Seller accepts the replacement request, Buyer shall be required to return the product to the Seller and only after return of the product, Seller shall be under obligation to provide the replacement product to the Buyer.</li>
                        <li>In case Seller rejects the replacement request, Buyer can choose to raise a dispute by contacting the customer care of THE M.A.I.D.C.</li>
                        <li>In case the Seller doesn't have the product at all, Seller can provide the refund to the Buyer and Buyer shall be under obligation to accept the refund in lieu of replacement.</li>
                        <li>All the product parameters shall be required to be complied within each case of replacement.</li>
                        <li>If the Seller doesn't respond to the Buyer's replacement request, within thirty (30) days from the date of replacement request placed by the Buyer, refund shall be processed in favour of Buyer and Seller shall be liable to refund amount paid to the Seller.</li>
                        <li>All shipping and other replacement charges shall be borne and incurred by the Seller.</li>
                    </ol>

                    <br></br>
                    <p><strong>12. REFUND POLICY :</strong></p>
                    <br></br>

                    <ol>
                        <li>The refund will be processed only after the product has been received by the Seller and it is found that -
                            <ul>
                                <li>The product was not damaged while in your possession.</li>
                                <li>The product is not different from what was shipped to you.</li>
                                <li>The product is returned in its original condition; and</li>
                                <li>Customer has submitted an unboxing video.</li>
                            </ul>
                        </li>
                        <li>The refund shall be processed only through the original mode of payment and in no other manner.</li>
                        <li>The maximum amount of refund for any transaction shall not exceed the total price paid by the Buyer for the concerned transaction or product that was ordered through the E-COMMERCE PLATFORM. In no case, shall THE M.A.I.D.C. be liable to pay any interest, compensation, or damages on the refund amount.</li>
                    </ol>

                    <br></br>
                    <p><strong> 13. CANCELLATION POLICY :</strong></p>
                    <br></br>

                    <ol>
                        <li>The order cancellation policy for each product shall be displayed on the product page as the same would be dependent on the type of product and its shelf life.</li>
                        <li>In any case, the Buyer would not be allowed to cancel the order for the product placed on the E-COMMERCE PLATFORM, once the product has been processed for delivery and dispatch.</li>
                        <li>If the Seller cancels the order, then the Seller shall provide a full refund including the payment gateway charges to the Buyer. The time line for the refund would be based on the terms & condition of the payment gateway service provider.</li>
                    </ol>
                    <br></br>
                    <p><strong>   14. PRIVACY POLICY :</strong></p>
                    <br></br>

                    <ol>
                        <li>Information collected and stored automatically: When you browse, read pages, or download information on the E-COMMERCE PLATFORM, we automatically gather and store certain technical information about your visit. This information never identifies who you are. The information we collect and store about your visit is listed below:
                            <ul>
                                <li>The IP address (IP address is a number that is automatically assigned to your computer whenever you’re surfing the web) from which you access the E-COMMERCE PLATFORM.</li>
                                <li>The type of internet browser (such as Chrome, Firefox, Netscape, or Internet Explorer) and operating system (Windows, Unix, Mac OS) used to access the E-COMMERCE PLATFORM.</li>
                                <li>The date and time you accessed the E-COMMERCE PLATFORM.</li>
                                <li>The pages/URLs on the E-COMMERCE PLATFORM you have visited; and</li>
                                <li>This information is only used to help us make the site more useful for you. With this data, we learn about the number of visitors to our site and the types of technology our visitors use.</li>
                            </ul>
                        </li>
                        <li>THE M.A.I.D.C. may collect the following information:
                            <ul>
                                <li>Name in full.</li>
                                <li>Contact information including email address.</li>
                                <li>Demographic information such as postcode, preferences, and interests; and</li>
                                <li>Other information relevant to customer surveys and/or offers.</li>
                            </ul>
                        </li>
                        <li>THE M.A.I.D.C. requires this information to understand your needs and provide you with a better service, and in particular for the following reasons:
                            <ul>
                                <li>Internal record keeping.</li>
                                <li>We may use the information to improve our products and services.</li>
                                <li>We may periodically send promotional emails about new products, special offers or other information which we think you may find interesting using the email address which you have provided.</li>
                                <li>From time to time, we may also use your information to contact you for market research purposes.</li>
                                <li>We may contact you by email, phone, fax or mail; and</li>
                                <li>We may use the information to customise the website according to your interests.</li>
                            </ul>
                        </li>
                        <li>Cookies :
                            <ul>
                                <li>When you visit our E-COMMERCE PLATFORM, automatically a small piece of software is downloaded on your computer/browsing device known as cookies. Some cookies collect personal information to recognize your computer in the future. THE M.A.I.D.C. only use non-persistent cookies or “per-session cookies”. Per-session cookies serve technical purposes, like providing seamless navigation through the E-COMMERCE PLATFORM. These cookies do not collect personal information on users and they are deleted as soon as you leave our website. The cookies do not permanently record data and they are not stored on your computer’s hard drive. The cookies are stored in memory and are only available during an active browser session. Again, once you close your browser, the cookie disappears.</li>
                            </ul>
                        </li>
                        <li>You understand that all your credit cards/debit cards/e-wallet or bank account related details will not be sold, shared, rented or leased by THE M.A.I.D.C. to any third party.</li>
                        <li>You expressly consent to THE M.A.I.D.C. sharing your credit cards/debit cards/e-wallet or bank account related details while contacting your bank or THE M.A.I.D.C.’s bank or the payment gateway provider used by you for making payment for THE M.A.I.D.C. ’s services, for the purpose of confirmation of payments made by you. You expressly consent to THE M.A.I.D.C. sharing your contact information like mobile number/phone number/email address/geographic address/G.S.T.I.N./P.A.N. to the shipping service partner or auditors or affiliates.</li>
                        <li>You expressly consent to THE M.A.I.D.C. holding to your personal identifiable information which includes but is not limited to your name, age, geographic address, email address, photograph, copies of documents which act as a proof of identification or address (includes but is not limited to your copies of passport, P.A.N. card, G.S.T.I.N. or driving license) and for the lawful / legitimate purpose of record and security during the subsistence of the User Agreement and for a period of 5 years after date of termination of the User Agreement or termination of User account.</li>
                        <li>You expressly consent that THE M.A.I.D.C. may store your contact information like mobile number/phone number/email address/ social media profile link for marketing purposes for a reasonable period after date of termination of the User Agreement or termination of User account, which may be further extended by you.</li>
                        <li>THE M.A.I.D.C. shall store all your information in electronic equipment under its control. You consent to THE M.A.I.D.C. contacting you for any promotional offers or marketing in the future, and you understand that this consent can be withdrawn by you at any point in time.</li>
                        <li>You expressly consent, that THE M.A.I.D.C. may from time to time, make your information and photographs available to third party entities for processing in respect of the services provided to you by THE M.A.I.D.C. or for statistical analysis.</li>
                        <li>Your information that THE M.A.I.D.C. holds including personal identifiable information or contact information or information will not be disclosed to any third party unless required by law. Although, THE M.A.I.D.C. shall use its best endeavor to protect the storage of your personal information from any cyber-attack or any attempt to illegally acquire your personal information, you agree that THE M.A.I.D.C. shall not be held responsible in any manner for, the leak or theft of your personal information or any consequential damage or loss (whether direct or indirect) caused to you by such a leak or theft.</li>
                    </ol>
                    <br></br>
                    <p><strong>       15. DISCLAIMER :</strong></p>
                    <br></br>

                    <ol>
                        <li>THE M.A.I.D.C. does not guarantee, represent or warrant that your use of our E-COMMERCE PLATFORM will be uninterrupted, timely, secure, or error-free. THE M.A.I.D.C. does not make any representation, warranties, or guarantees about the availability of the E-COMMERCE PLATFORM or any specific function of the E-COMMERCE PLATFORM at all times or any service level commitment about the E-COMMERCE PLATFORM or its specific function. THE M.A.I.D.C. does not warrant that the results that may be obtained from the use of the E-COMMERCE PLATFORM will be accurate or reliable.</li>
                        <li>THE M.A.I.D.C. reserves the right to refuse access to the E-COMMERCE PLATFORM, terminate User accounts, remove, limit access, or edit content at any time without notice to the User.</li>
                        <li>You expressly agree that your use of, or inability to use, the service is at your sole risk. The E-COMMERCE PLATFORM and all products and services delivered to you through the E-COMMERCE PLATFORM are (except as expressly stated by us) provided 'as is' and 'as available' for your use, without any representation, warranties or conditions of any kind, either express or implied, including all implied warranties or conditions of merchantability, merchantable quality, legality, fitness for a particular purpose, import, durability, title, usage, and non-infringement.</li>
                        <li>Notwithstanding its reasonable efforts in that behalf, THE M.A.I.D.C. cannot take responsibility or control the information provided by other Users which is made available on the E-COMMERCE PLATFORM.</li>
                    </ol>
                    <br></br>
                    <p><strong>      16. INDEMNITY TO THE M.A.I.D.C. :</strong></p>
                    <br></br>

                    <ol>
                        <li>User understands and agrees that User shall promptly on demand, without limitation, indemnify, hold harmless, protect from liability and/or defend THE M.A.I.D.C., its affiliates and their respective officers, directors, proprietors, partners, managers, members, trustees, shareholders, employees and agents (“Indemnified Parties”) for and against all claims, liabilities, costs and expenses (including attorney’s fees) incurred or to be incurred by the Indemnified Parties that arise out of, in any way relate to, or result from any breach by the User of any of the provisions of Terms of Use, Seller User Agreement, policies, circular, directions, guidelines, or breach of any laws by the User, or negligence, fraud or willful misconduct of the User or its affiliates and their respective officers, directors, shareholders, employees, contractors, sub-contractors, agents and personnel.</li>
                        <li>For the avoidance of doubt, it is further clarified that the right to indemnification in connection with any of the aforesaid claims or cause of action is independent and in addition to other rights and remedies of the Indemnified Person that may be available at law or in equity.</li>
                    </ol>
                    <br></br>
                    <p><strong>     17. LIMITATION OF THE M.A.I.D.C. ’S LIABILITY & RELEASE :</strong></p>
                    <br></br>

                    <ol>
                        <li>User hereby expressly release THE M.A.I.D.C. and/or its Affiliates and/or any of its officers and representatives from any cost, damage, liability, or other consequence of any of the actions/inactions of the Seller and specifically waiver any claims or demands that User may have in this behalf under any statute, contract, or otherwise. User agrees to execute any claim/liability waivers document which THE M.A.I.D.C. may provide from time to time.</li>
                        <li>Without prejudice to the forgoing, in any case, the monetary liability of THE M.A.I.D.C. to the Seller for any act of default, fraud, or negligence, shall not exceed the amount paid as E-COMMERCE PLATFORM Usage Fees per annum, by such User.</li>
                        <li>Without prejudice to the forgoing, in any case, the monetary liability of THE M.A.I.D.C. to the Buyer for any act of default, fraud, or negligence, shall not exceed the amount for the particular transaction / order paid by such User.</li>
                    </ol>
                    <br></br>
                    <p><strong>    18. SHIPPING & DELIVERY POLICY :</strong></p>
                    <br></br>

                    <ul>
                        <li>18.1 The User, who is a Buyer, may also select the shipping service provider for shipping the products and bear the cost of shipping based on the quotes displayed on the E-COMMERCE PLATFORM by the shipping service provider.</li>
                        <li>18.2 THE M.A.I.D.C. does not make any representation, warranties, or guarantees in respect to the service provided by it or the E-COMMERCE PLATFORM or the services/products of the third-party service provider listed on the E-COMMERCE PLATFORM.</li>
                        <li>18.3 The information in relation to third party service provider such delivery timelines provided by the shipping service provider are provided are on an “as is” basis and you agree to use these third-party services at your own risk.</li>
                        <li>18.4 You have acquainted yourself with the terms and conditions and privacy policy of such shipping service providers, before using the shipping service provider services which can be seen here: [please insert link to shipping service provider services]</li>
                        <li>18.5 You agree that you won’t hold THE M.A.I.D.C. liable for any delay, damage, loss, pilferage, or destruction of the products caused by the shipping service provider or for any destruction, theft, or leak of any data including personal data from the shipping service provider application on the E-COMMERCE PLATFORM or the shipping service provider’s database.</li>
                    </ul>
                    <br></br>
                    <p><strong>     19. GRIEVANCE REDRESSAL MECHANISM :</strong></p>
                    <br></br>

                    <ul>
                        <li>19.1 A User who purchases or sells products on the E-COMMERCE PLATFORM and has any grievances in respect of the product or payment should first contact the customer care / grievance cell of the Buyer or Seller, as the case may be, and try resolve any such grievances in mutually acceptable manner. If the User is not satisfied by the resolution, then within 30 days from the date of delivery of the product the User can avail the Level 1 to Level 4 of the Grievance Redressal Mechanism provided below.</li>
                        <li>19.2 The Grievance Redressal Mechanism can handle grievances, applications, or clarifications provided in respect to and under the terms of the provisions of:
                            <ul>
                                <li>I. The Information technology Act, 2000.</li>
                                <li>II. Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021.</li>
                                <li>III. Information Technology (Reasonable security practices and procedures and sensitive personal data or information) Rules, 2011.</li>
                                <li>IV. The Consumer Protection Act, 2019; and</li>
                                <li>V. Consumer Protection (E-Commerce) Rules, 2020.</li>
                            </ul>
                        </li>
                        <li>19.3 Level 1: In case the User has any query, grievance, or needs any assistance then such User may approach the customer care of THE M.A.I.D.C.
                            <ul>
                                <li>Customer Care Email details: support@mahaagromart.com</li>
                                <li>Telephone no: 8888842300</li>
                            </ul>
                        </li>
                        <li>19.4 Level 2: In case the User is not satisfied with resolution provided under Level 1, then such User may approach the Grievance Redressal officer of THE M.A.I.D.C. whose details are provided below:
                            <ul>
                                <li>Name of Grievance Officer: Kishor Gokul Rathod</li>
                                <li>Email details: admin@mahaagromart.com</li>
                            </ul>
                        </li>
                        <li>19.5 Level 3: In case the User is not satisfied with resolution provided under Level 2, then such User may approach the Nodal officer of THE M.A.I.D.C. whose details are provided below:
                            <ul>
                                <li>Name of Nodal Officer: Kishor Gokul Rathod</li>
                                <li>Email details: info@mahagromart.com</li>
                            </ul>
                        </li>
                    </ul>
                    <br></br>
                    <p><strong>     20. HYPERLINKING POLICY :</strong></p>
                    <br></br>

                    <ul>
                        <li>20.1 Links to external websites/portals: At many places in the E-COMMERCE PLATFORM, you shall find links to other websites/portals which have been placed for your convenience. THE M.A.I.D.C.is not responsible for the contents and reliability of the linked websites/portals and does not endorse the views expressed in them. Mere presence of the link or its listing on E-COMMERCE PLATFORM should not be assumed as endorsement of any kind. THE M.A.I.D.C. cannot guarantee that these links will work all the time and THE M.A.I.D.C. has no control over availability of linked pages.</li>
                        <li>20.2 Links to E-COMMERCE PLATFORM by other websites: THE M.A.I.D.C. does not object to you linking directly to the information that is hosted on this E-COMMERCE PLATFORM and no prior permission from THE M.A.I.D.C. is required for the same.</li>
                        <li>20.3 THE M.A.I.D.C. does not permit any of the E-COMMERCE PLATFORM’s pages to be loaded into frames on any website or portal. The pages belonging to this E-COMMERCE PLATFORM must load into a newly opened browser window.</li>
                    </ul>
                    <br></br>
                    <p><strong>     21. ASSIGNMENT AND SUB-CONTRACTING :</strong></p>
                    <br></br>


                    <ul>
                        <li>21.1 User shall not assign any of its rights, obligations or responsibilities under this Terms of Use without the prior written consent of THE M.A.I.D.C. and in absence of such consent, any such assignment shall be null and void.</li>
                        <li>21.2 All terms and conditions of this Terms of Use shall be binding upon and shall inure to the benefit of the Parties hereto and their successors and authorized assignees. User understands, acknowledges and agrees that THE M.A.I.D.C. may sub-contract one or more of its services to any third-party.</li>
                    </ul>
                    <br></br>
                    <p><strong>     22. FORCE MAJEURE :</strong></p>
                    <br></br>

                    <ul>
                        <li>22.1 THE M.A.I.D.C. or any User shall be under no liability whatsoever in respect to its obligations to another User in a transaction, in the event of non-availability of the E-COMMERCE PLATFORM and/or any of the products, goods, services, or any portion thereof, occasioned by or is due to any of the following causes (which events and/or circumstances are hereinafter referred to as “Force Majeure”), to the extent beyond its reasonable control: acts of God, floods, government regulations including lockdown, accident, riots, war, terrorist acts, epidemic, pandemic, quarantine, civil commotion, breakdown of communication facilities, breakdown of web host, breakdown of internet service provider, natural catastrophes, governmental acts or omissions, changes in laws or regulations, national strikes, fire, explosion, generalized lack of availability of raw materials or energy.</li>
                    </ul>
                    <br></br>
                    <p><strong>       23. GOVERNING LAW & ARBITRATION :</strong></p>
                    <br></br>

                    <ul>
                        <li>23.1 The Terms of Use shall be governed by the laws of the Republic of India, as applicable to the city of Mumbai.</li>
                        <li>23.2 In the event of any dispute or difference between parties relating arising from, or connected with the Terms of Use, including any interpretation thereof, the same shall be referred to adjudication to a sole arbitrator to be appointed parties mutually as per the terms of the Arbitration and Conciliation Act, 1999 and the decision of the said sole arbitrator shall be binding on the parties and would be final and conclusive.</li>
                        <li>23.3 The venue and seat of the arbitration shall be Mumbai, Maharashtra.</li>
                    </ul>



                    <h2>Laws & Jurisdiction</h2>
                    <p>These Terms of Use shall be governed by the laws of India, without giving effect to its conflict of law’s provisions. Any dispute arising out of or in relation to these Terms of Use shall be subject to the exclusive jurisdiction of courts at Mumbai, Maharashtra, India.</p>
                </div>
            </div>
        </div>
    );
};

export default TermsAndConditions;
